server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: files/**
mybatis:
  mapper-locations: mapper/*.xml


#jwt:
#  config:
#    key: userlogin
#    failureTime: 3600000
#    tokenPrefix: "Authorization"
#    tokenHeader: "Bearer "
#    iss: "pkm"

