package cn.edu.ecnu.domain;

import java.io.Serializable;

public class Project implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectname
     *
     * @mbggenerated
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.stage
     *
     * @mbggenerated
     */
    private Integer stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.midmark
     *
     * @mbggenerated
     */
    private Integer midmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.finalmark
     *
     * @mbggenerated
     */
    private Integer finalmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.advisorid
     *
     * @mbggenerated
     */
    private String advisorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.teamid
     *
     * @mbggenerated
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pid
     *
     * @return the value of project.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pid
     *
     * @param pid the value for project.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectname
     *
     * @return the value of project.projectname
     *
     * @mbggenerated
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectname
     *
     * @param projectname the value for project.projectname
     *
     * @mbggenerated
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.description
     *
     * @return the value of project.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.description
     *
     * @param description the value for project.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.type
     *
     * @return the value of project.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.type
     *
     * @param type the value for project.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.stage
     *
     * @return the value of project.stage
     *
     * @mbggenerated
     */
    public Integer getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.stage
     *
     * @param stage the value for project.stage
     *
     * @mbggenerated
     */
    public void setStage(Integer stage) {
        this.stage = stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.midmark
     *
     * @return the value of project.midmark
     *
     * @mbggenerated
     */
    public Integer getMidmark() {
        return midmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.midmark
     *
     * @param midmark the value for project.midmark
     *
     * @mbggenerated
     */
    public void setMidmark(Integer midmark) {
        this.midmark = midmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.finalmark
     *
     * @return the value of project.finalmark
     *
     * @mbggenerated
     */
    public Integer getFinalmark() {
        return finalmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.finalmark
     *
     * @param finalmark the value for project.finalmark
     *
     * @mbggenerated
     */
    public void setFinalmark(Integer finalmark) {
        this.finalmark = finalmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.advisorid
     *
     * @return the value of project.advisorid
     *
     * @mbggenerated
     */
    public String getAdvisorid() {
        return advisorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.advisorid
     *
     * @param advisorid the value for project.advisorid
     *
     * @mbggenerated
     */
    public void setAdvisorid(String advisorid) {
        this.advisorid = advisorid == null ? null : advisorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.teamid
     *
     * @return the value of project.teamid
     *
     * @mbggenerated
     */
    public String getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.teamid
     *
     * @param teamid the value for project.teamid
     *
     * @mbggenerated
     */
    public void setTeamid(String teamid) {
        this.teamid = teamid == null ? null : teamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", projectname=").append(projectname);
        sb.append(", description=").append(description);
        sb.append(", type=").append(type);
        sb.append(", stage=").append(stage);
        sb.append(", midmark=").append(midmark);
        sb.append(", finalmark=").append(finalmark);
        sb.append(", advisorid=").append(advisorid);
        sb.append(", teamid=").append(teamid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}