package cn.edu.ecnu.domain;

import java.io.Serializable;

public class Team implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.teamid
     *
     * @mbggenerated
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.teamname
     *
     * @mbggenerated
     */
    private String teamname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.teamid
     *
     * @return the value of team.teamid
     *
     * @mbggenerated
     */
    public String getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.teamid
     *
     * @param teamid the value for team.teamid
     *
     * @mbggenerated
     */
    public void setTeamid(String teamid) {
        this.teamid = teamid == null ? null : teamid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.teamname
     *
     * @return the value of team.teamname
     *
     * @mbggenerated
     */
    public String getTeamname() {
        return teamname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.teamname
     *
     * @param teamname the value for team.teamname
     *
     * @mbggenerated
     */
    public void setTeamname(String teamname) {
        this.teamname = teamname == null ? null : teamname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teamid=").append(teamid);
        sb.append(", teamname=").append(teamname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}